# Generated by Django 5.2.1 on 2025-07-21 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_datasource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureToggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('maintenance', models.BooleanField(default=False)),
                ('super_user_only', models.BooleanField(default=False, help_text='Only superusers can access this feature')),
                ('coming_soon', models.BooleanField(default=False)),
                ('coming_soon_percent', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
