# Generated by Django 5.2.1 on 2025-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0009_featuretoggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(help_text='Enter your change note here...')),
                ('link_text', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
