# Generated by Django 5.2.1 on 2025-08-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0012_add_custom_style'),
        ('busstops', '0012_improve_featuretoggle'),
    ]

    operations = [
    ]
