# Generated by Django 5.2.1 on 2025-08-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0013_merge_20250818_0149'),
        ('busstops', '0014_add_default_change_note_tags'),
    ]

    operations = [
    ]
