# Generated by Django 5.2.1 on 2025-08-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0015_add_notification_banner'),
        ('busstops', '0015_merge_20250818_0241'),
    ]

    operations = [
    ]
