# Generated by Django 5.2.1 on 2025-08-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0016_add_custom_style_path_targeting'),
        ('busstops', '0016_merge_20250818_0437'),
    ]

    operations = [
    ]
