# Generated by Django 5.2.1 on 2025-08-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_fix_custom_style_line_endings'),
        ('busstops', '0017_merge_20250818_1203'),
    ]

    operations = [
    ]
