# Generated by Django 5.2.1 on 2025-08-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0018_add_favourite_model'),
        ('busstops', '0018_merge_20250818_1307'),
    ]

    operations = [
    ]
