# Generated by Django 5.2.1 on 2025-08-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0019_add_object_id_str_to_favourite'),
        ('busstops', '0019_merge_20250818_1447'),
    ]

    operations = [
    ]
