# Generated by Django 5.2.1 on 2025-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0020_add_cached_display_fields_to_favourite'),
        ('busstops', '0020_merge_20250818_1606'),
    ]

    operations = [
    ]
