# Generated by Django 5.2.1 on 2025-08-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0021_merge_20250818_1631'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_user_favourite',
        ),
    ]
