# Generated by Django 5.2.1 on 2025-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_remove_vehiclerevision_score_delete_vehicleeditvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='style',
            field=models.CharField(blank=True, choices=[('Single Decker', 'Single Decker'), ('Double Decker', 'Double Decker'), ('Minibus', 'Minibus'), ('Coach', 'Coach'), ('articulated', 'articulated'), ('train', 'train'), ('tram', 'tram'), ('amphibious', 'amphibious')], max_length=13),
        ),
    ]
