# Generated by Django 5.2.1 on 2025-08-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_vehicletype_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkVehicleCreation',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Vehicle Creation',
                'verbose_name_plural': 'Bulk Vehicle Creation',
                'permissions': [('bulk_add_vehicle', 'Can bulk add vehicles')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.vehicle',),
        ),
    ]
